version: '3.8'

services:

  # MQTT DMX Sequencer
  mqtt-dmx-sequencer:
    build: ./mqtt-dmx-sequencer
    container_name: mqtt-dmx-sequencer
    network_mode: host
    #volumes:
    #  - ./config:/app/config
    #  - ./settings.json:/app/settings.json
    #  - ./config.json:/app/config.json
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

